// The decks. Written once, by hand, and then never consulted again at roll time —
// which is the whole point. A language model asked for "a tattoo idea" collapses
// onto snake / moth / dagger / ouroboros every time; a language model asked to
// write six long lists once, and then forbidden from choosing between them,
// doesn't. Surprise lives in the cross-product, not in taste.
//
// Sizes are deliberate. ~210 lineages × ~100 techniques × ~100 formats ×
// ~120 constraints × ~120 twists is upwards of 3×10^10 combinations before the
// subject is even drawn, which is more than a lifetime of rolling.
//
// Each entry: { v } display value, { note } one line of what it actually means,
// { q } extra search terms handed to the Met / Commons queries. Where q is
// absent the sketch falls back to the entry's own name.

// -------------------------------------------------------------------- lineage
// The visual tradition the piece is drawn *inside*. Not a mood — a set of rules
// somebody else already worked out, which you can then break on purpose. Grouped
// by where they came from, only so the list stays honestly spread rather than
// drifting into five hundred years of one continent.
export const LINEAGE = [
  // ---- East and Central Asia
  { v: 'Edo-period ukiyo-e', note: 'flat colour fields; the contour line does all the work', q: 'ukiyo-e woodblock' },
  { v: 'horimono bodysuit', note: 'wind bars and water in the background carry the figure', q: 'Kuniyoshi warrior print' },
  { v: 'Japanese kamon', note: 'an entire animal fitted inside a circle at 3cm and still legible', q: 'kamon Japanese crest' },
  { v: 'sumi-e', note: 'one loaded brush, one pass, no correction possible', q: 'ink painting brush' },
  { v: 'Rinpa screen', note: 'gold ground, no horizon, plants at architectural scale', q: 'Rinpa screen Japanese' },
  { v: 'katagami stencil', note: 'the pattern must hold together as one connected piece of paper', q: 'katagami stencil' },
  { v: 'maki-e lacquer', note: 'gold dust laid into black; the image is a deposit, not a stroke', q: 'maki-e lacquer' },
  { v: 'netsuke carving', note: 'a whole scene solved inside 4cm of boxwood, with no fragile parts', q: 'netsuke' },
  { v: 'Zen ensō', note: 'a single circle that records the state you drew it in', q: 'enso Zen calligraphy' },
  { v: 'hikeshi banten', note: 'a firefighter\'s coat: the good picture is on the inside', q: 'Japanese fireman coat' },
  { v: 'sashiko stitching', note: 'repair as pattern; the grid comes from the weave', q: 'sashiko stitching' },
  { v: 'Ainu kaparamip', note: 'thorn-and-bracket patterns guarding the openings of a garment', q: 'Ainu textile' },
  { v: 'Ryukyuan bingata', note: 'tropical colour under a stencil discipline', q: 'bingata Okinawa textile' },
  { v: 'oracle bone script', note: 'writing designed to be cracked by fire and then read', q: 'oracle bone script' },
  { v: 'Shang bronze taotie', note: 'a face you only resolve once you stop looking for one', q: 'Chinese ritual bronze vessel' },
  { v: 'Song bird-and-flower painting', note: 'unsentimental observation at the scale of a fan', q: 'Song dynasty bird flower painting' },
  { v: 'Chinese seal script', note: 'characters compressed to fill a square exactly', q: 'seal script Chinese calligraphy' },
  { v: 'nianhua New Year print', note: 'cheap, bright, printed by the thousand, pasted on a door', q: 'Chinese New Year print' },
  { v: 'Korean minhwa', note: 'folk painting that cheerfully ignores proportion', q: 'minhwa Korean folk painting' },
  { v: 'Goryeo celadon inlay', note: 'white slip cut into grey-green glaze; line as an inlaid groove', q: 'Goryeo celadon inlaid' },
  { v: 'Tibetan thangka', note: 'every figure sits on a grid of prescribed proportions', q: 'thangka Tibetan' },
  { v: 'Mongolian soyombo', note: 'a script invented once, for one purpose, by one person', q: 'Soyombo symbol' },
  { v: 'Chinese papercut', note: 'everything must stay attached to everything else', q: 'Chinese papercut' },
  { v: 'Dunhuang cave mural', note: 'pigment on plaster, in the dark, for no audience', q: 'Dunhuang mural' },
  { v: 'ema votive tablet', note: 'a wish painted on wood and hung outdoors to weather', q: 'ema votive tablet Japan' },
  { v: 'shan shui landscape', note: 'distance is done with washes and omission, never with size', q: 'shan shui Chinese landscape' },
  { v: 'yūrei ghost print', note: 'the figure fades out below the waist because it has to', q: 'Japanese ghost print yurei' },
  { v: 'Đông Hồ print', note: 'printed on paper coated in crushed shell, colours from leaves and rust', q: 'Dong Ho painting' },
  { v: 'stone-stele rubbing', note: 'white line on black, taken off a carving rather than drawn', q: 'stone rubbing stele Chinese' },
  { v: 'mingei folk craft', note: 'made by an anonymous hand for use, not for looking at', q: 'mingei Japanese folk craft' },

  // ---- South and Southeast Asia
  { v: 'Mughal album border', note: 'the frame is more elaborate than the thing it frames', q: 'Mughal album border' },
  { v: 'Persian miniature', note: 'no cast shadows anywhere; depth is stacking, not lighting', q: 'Persian miniature painting' },
  { v: 'Rajput painting', note: 'flat saturated grounds; emotion carried entirely by colour', q: 'Rajput painting' },
  { v: 'Pahari painting', note: 'landscape as a stage flat behind very precise figures', q: 'Pahari painting' },
  { v: 'Madhubani', note: 'every empty area gets filled; the horror of a blank ground', q: 'Madhubani painting' },
  { v: 'Warli', note: 'the entire human figure is two triangles and a circle', q: 'Warli painting' },
  { v: 'Gond art', note: 'the body is filled with a repeating mark that is its own texture', q: 'Gond painting' },
  { v: 'Pattachitra', note: 'a hard black outline, then colour, then the outline again on top', q: 'Pattachitra painting' },
  { v: 'kalamkari', note: 'drawn with a bamboo pen and fermented iron; the black comes up slowly', q: 'Kalamkari textile' },
  { v: 'Jain cosmological diagram', note: 'the universe drawn as a plan and elevation', q: 'Jain cosmology manuscript' },
  { v: 'Kamasan painting', note: 'Balinese narrative in registers, read like a comic strip', q: 'Kamasan Balinese painting' },
  { v: 'Javanese batik', note: 'wax resist: you draw where the colour will not go', q: 'batik Java' },
  { v: 'Thai temple mural', note: 'gold on red, crowds of tiny figures, no vanishing point', q: 'Thai temple mural' },
  { v: 'yantra tattoo', note: 'script and diagram as a functional object worn on the body', q: 'yantra diagram' },
  { v: 'Angkor bas-relief', note: 'shallow carving that only reads in raking light', q: 'Angkor bas relief' },
  { v: 'Burmese parabaik', note: 'a folding book that opens into one continuous panorama', q: 'parabaik Burmese manuscript' },
  { v: 'Sri Lankan mask carving', note: 'exaggeration calibrated to be read from a distance at night', q: 'Sri Lankan mask' },

  // ---- West Asia and the Islamic world
  { v: 'Ottoman tughra', note: 'a name grown into a monogram until it stops being letters', q: 'tughra' },
  { v: 'İznik tile', note: 'the palette is fixed by the kiln, not by preference', q: 'Iznik tile' },
  { v: 'girih strapwork', note: 'a tiling that never repeats where you expect it to', q: 'girih Islamic geometric' },
  { v: 'kufic calligraphy', note: 'letters squared off until they become masonry', q: 'Kufic calligraphy' },
  { v: 'Mamluk inlaid metalwork', note: 'silver hammered into brass; the drawing is a wound', q: 'Mamluk inlaid metalwork' },
  { v: 'Persian carpet medallion', note: 'a centre, four corners, and a border that resolves them', q: 'Persian carpet medallion' },
  { v: 'muqarnas vaulting', note: 'a curve built entirely out of stacked flat facets', q: 'muqarnas' },
  { v: 'Safavid tilework', note: 'cut-tile mosaic where every colour is a separate piece', q: 'Safavid tile' },
  { v: 'khachkar', note: 'an Armenian cross-stone: infinite knotwork around one fixed form', q: 'khachkar' },
  { v: 'Yemeni silver filigree', note: 'granulation and wire; mass built out of nothing but edges', q: 'Yemeni silver jewellery' },
  { v: 'Turkmen carpet gul', note: 'one motif, repeated, that identifies a whole people', q: 'Turkmen carpet' },
  { v: 'ebru marbling', note: 'the image is floated, then lifted; it can never be revised', q: 'ebru marbled paper' },
  { v: 'Achaemenid relief', note: 'procession in perfect profile, everyone the same height', q: 'Persepolis relief' },
  { v: 'Hebrew micrography', note: 'a picture drawn entirely out of very small writing', q: 'micrography Hebrew manuscript' },
  { v: 'Sumerian cylinder seal', note: 'a scene built to repeat forever when it is rolled', q: 'cylinder seal impression' },

  // ---- Africa
  { v: 'Adinkra stamp', note: 'a proverb carved into a calabash and printed by hand', q: 'Adinkra' },
  { v: 'Kuba raffia cloth', note: 'a pattern that deliberately breaks its own rule partway across', q: 'Kuba cloth' },
  { v: 'Ndebele wall painting', note: 'hard-edged colour fields drawn freehand, straight to the wall', q: 'Ndebele house painting' },
  { v: 'Amazigh tattoo marks', note: 'a small closed vocabulary of protective marks on face and hands', q: 'Amazigh Berber jewellery' },
  { v: 'Egyptian tomb painting', note: 'each body part drawn from its most recognisable angle', q: 'Egyptian tomb painting' },
  { v: 'hieroglyphic relief', note: 'writing and picture with no border between them', q: 'hieroglyphs relief Egypt' },
  { v: 'Ethiopian magic scroll', note: 'made to your own height, to be buried with you', q: 'Ethiopian magic scroll' },
  { v: 'Ethiopian gospel illumination', note: 'enormous eyes, flat colour, no attempt at likeness', q: 'Ethiopian manuscript illumination' },
  { v: 'adire eleko', note: 'cassava-paste resist, drawn freehand, always slightly irregular', q: 'adire textile Yoruba' },
  { v: 'nsibidi', note: 'an ideographic system you were not supposed to be taught', q: 'Nsibidi' },
  { v: 'Bwa plank mask', note: 'pure geometry — chevrons, targets, a hooked beak — in black and white', q: 'Bwa mask Burkina Faso' },
  { v: 'Tuareg silverwork', note: 'engraved geometry on a cross whose meaning is a place', q: 'Tuareg jewellery' },
  { v: 'Akan goldweight', note: 'a tiny cast brass object that is also a unit of measurement', q: 'Akan goldweight' },
  { v: 'Meroitic relief', note: 'Egyptian grammar spoken with a Nubian accent', q: 'Meroe Nubia relief' },
  { v: 'Songye kifwebe striation', note: 'the whole surface cut into parallel grooves', q: 'Songye kifwebe mask' },

  // ---- Oceania
  { v: 'Marquesan patutiki', note: 'the body is divided first; the pattern only fills the divisions', q: 'Marquesas tattoo' },
  { v: 'kōwhaiwhai', note: 'painted rafter patterns: koru unrolling along a beam', q: 'kowhaiwhai pattern' },
  { v: 'tā moko', note: 'chiselled rather than punctured, so the skin is grooved', q: 'ta moko Maori' },
  { v: 'Samoan pe\'a', note: 'a single continuous garment of ink from waist to knee', q: 'Samoan tatau' },
  { v: 'Hawaiian kākau', note: 'solid black geometry, asymmetric by design', q: 'Hawaiian tattoo' },
  { v: 'Iban pantang', note: 'hooked spirals and solid black, made to be worn rather than shown', q: 'Iban Borneo tattoo' },
  { v: 'Aboriginal x-ray painting', note: 'the skeleton and organs drawn inside the outline', q: 'Aboriginal rock art' },
  { v: 'Papuan barkcloth', note: 'freehand asymmetry on a beaten, irregular ground', q: 'barkcloth Papua' },
  { v: 'Lapita pottery stamp', note: 'dentate stamping — the pattern is a row of tooth marks', q: 'Lapita pottery' },
  { v: 'rongorongo', note: 'a script nobody alive can read, carved boustrophedon', q: 'rongorongo' },

  // ---- The Americas
  { v: 'Aztec codex', note: 'outline plus flat fill; the glyph and the picture are the same object', q: 'Aztec codex' },
  { v: 'Maya stela glyph', note: 'every glyph block is a square you must fill completely', q: 'Maya stela glyph' },
  { v: 'Nazca line', note: 'drawn at a scale where you can never see the whole thing', q: 'Nazca lines' },
  { v: 'Moche stirrup vessel', note: 'line painting wrapped around a form that has no flat side', q: 'Moche pottery' },
  { v: 'Haida formline', note: 'ovoids and U-forms; the negative shapes are named and rule-bound', q: 'Haida formline' },
  { v: 'Chilkat weaving', note: 'formline translated into a medium that cannot do a curve', q: 'Chilkat blanket' },
  { v: 'Navajo weaving', note: 'diamond geometry with a deliberate flaw left in', q: 'Navajo blanket' },
  { v: 'Mimbres pottery', note: 'an animal in a bowl, with a hole punched through it', q: 'Mimbres pottery' },
  { v: 'Inuit stonecut print', note: 'a solid silhouette with the barest interior line', q: 'Inuit stonecut print' },
  { v: 'Chicano fineline', note: 'single needle, soft grey, photographic patience', q: 'Chicano mural' },
  { v: 'lotería card', note: 'one object, centred, named underneath, nothing else', q: 'Loteria Mexican card' },
  { v: 'Posada calavera', note: 'skeletons doing entirely ordinary things, at speed', q: 'Posada calavera' },
  { v: 'Taíno petroglyph', note: 'a face reduced to two pits and a line, pecked into rock', q: 'Taino petroglyph' },
  { v: 'Shipibo kené', note: 'an unbroken labyrinth said to be the notation of a song', q: 'Shipibo textile' },
  { v: 'Plains ledger art', note: 'drawn on stolen accounting paper; the ruled lines stay visible', q: 'ledger art Plains' },
  { v: 'Wari tunic', note: 'a figure abstracted until it is only a rhythm of blocks', q: 'Wari tunic Andes' },

  // ---- Ancient and medieval Europe
  { v: 'Greek black-figure', note: 'detail incised *through* the black, not painted on', q: 'black-figure vase' },
  { v: 'Greek red-figure', note: 'the same job done in reverse, and suddenly anatomy is possible', q: 'red-figure vase' },
  { v: 'Roman floor mosaic', note: 'the image is assembled from units you could count', q: 'Roman mosaic' },
  { v: 'Byzantine mosaic', note: 'gold tesserae set at an angle so the ground flickers', q: 'Byzantine mosaic' },
  { v: 'Etruscan bronze mirror', note: 'incised line on a curved metal field, drawn to be seen in reflection', q: 'Etruscan mirror engraved' },
  { v: 'Scythian animal style', note: 'predator and prey folded into one closed contour', q: 'Scythian gold animal' },
  { v: 'Minoan fresco', note: 'painted into wet plaster, so every decision is final and fast', q: 'Minoan fresco' },
  { v: 'Cycladic figurine', note: 'a human being reduced to a nose', q: 'Cycladic figurine' },
  { v: 'Pictish symbol stone', note: 'a vocabulary of symbols nobody has ever decoded', q: 'Pictish symbol stone' },
  { v: 'runestone carving', note: 'the beast\'s own body is the ribbon the text runs along', q: 'runestone' },
  { v: 'Urnes style', note: 'animals so attenuated they have become pure interlace', q: 'Urnes style' },
  { v: 'insular knotwork', note: 'one line, no ends, obsessive over-and-under', q: 'insular manuscript interlace' },
  { v: 'Book of Kells', note: 'ornament at a density that stops being legible and becomes texture', q: 'Book of Kells' },
  { v: 'Bayeux embroidery', note: 'a continuous strip with the commentary running along the edges', q: 'Bayeux Tapestry' },
  { v: 'Romanesque tympanum', note: 'figures scaled by importance and squeezed to fit the arch', q: 'Romanesque tympanum' },
  { v: 'Gothic tracery', note: 'stone drawn as though it were line, carrying real load', q: 'Gothic tracery window' },
  { v: 'misericord carving', note: 'the joke carved underneath the seat, where nobody looks', q: 'misericord carving' },
  { v: 'medieval bestiary', note: 'an animal drawn by someone who had only been told about it', q: 'bestiary manuscript' },
  { v: 'marginal drollery', note: 'whatever the scribe felt like, in the space left over', q: 'marginalia manuscript grotesque' },
  { v: 'danse macabre', note: 'everyone, in order of rank, led away by the same figure', q: 'danse macabre' },
  { v: 'memento mori engraving', note: 'a skull, an hourglass, and an unreasonable amount of drapery', q: 'memento mori vanitas' },
  { v: 'heraldic achievement', note: 'a strict grammar of tinctures, charges and impossible animals', q: 'coat of arms heraldry' },
  { v: 'blackletter', note: 'verticals so heavy the counters nearly close up', q: 'blackletter manuscript' },
  { v: 'Coptic textile', note: 'figures reduced to what a loop of thread can say', q: 'Coptic textile fragment' },

  // ---- Early modern Europe
  { v: 'Dürer woodcut', note: 'black line under enormous pressure; nothing is soft', q: 'Durer woodcut' },
  { v: 'Dutch Golden Age engraving', note: 'every value built from swelling parallel lines; no grey ink exists', q: 'engraving Netherlands 17th century' },
  { v: 'Rembrandt etching', note: 'the darkest passages are the ones he stopped controlling', q: 'Rembrandt etching' },
  { v: 'Callot etching', note: 'hundreds of figures, each about 4mm tall, each doing something', q: 'Jacques Callot etching' },
  { v: 'Piranesi etching', note: 'architecture drawn at a scale that cannot exist', q: 'Piranesi etching' },
  { v: 'Hogarth engraving', note: 'a narrative in which every object in the room is evidence', q: 'Hogarth engraving' },
  { v: 'Goya aquatint', note: 'a flat velvety black that no line could produce', q: 'Goya Caprichos' },
  { v: 'Blake relief etching', note: 'text and image bitten from the same plate at once', q: 'William Blake illuminated' },
  { v: 'Vesalius anatomical plate', note: 'the flayed figure posed as though it were enjoying itself', q: 'Vesalius anatomy' },
  { v: 'herbal woodcut', note: 'the roots drawn as carefully as the flower', q: 'herbal woodcut plant' },
  { v: 'portolan chart', note: 'rhumb lines, a compass rose, and something terrible at the margin', q: 'portolan chart' },
  { v: 'emblem book', note: 'a motto, a picture, and an explanation that fits neither', q: 'emblem book' },
  { v: 'alchemical emblem', note: 'the picture is a coded instruction, not an illustration', q: 'alchemical emblem' },
  { v: 'Solomonic sigil', note: 'geometry drawn to be functional rather than pretty', q: 'magic seal grimoire' },
  { v: 'Tarot de Marseille', note: 'flat, wrongly perspectived, and impossible to forget', q: 'tarot card woodcut' },
  { v: 'Wunderkammer plate', note: 'unrelated objects arranged as though the arrangement were an argument', q: 'cabinet of curiosities' },
  { v: 'scrimshaw', note: 'engraved on a curve, at sea, with whatever was to hand', q: 'scrimshaw' },
  { v: 'ex libris bookplate', note: 'a whole cosmology compressed into 60 millimetres', q: 'ex libris bookplate' },
  { v: 'silhouette portrait', note: 'a likeness with literally no interior information', q: 'silhouette portrait' },
  { v: 'chapbook woodcut', note: 'a worn block reused for whatever story needed a picture', q: 'chapbook woodcut' },
  { v: 'broadside ballad', note: 'type and image jammed together to fit one sheet', q: 'broadside ballad' },
  { v: 'Delftware blue', note: 'one colour, painted fast on unforgiving raw glaze', q: 'Delftware tile' },
  { v: 'anatomical écorché', note: 'a body standing calmly with its skin held in one hand', q: 'ecorche anatomical figure' },

  // ---- The nineteenth century
  { v: 'Haeckel plate', note: 'symmetry pushed past biology and into ornament', q: 'Haeckel Kunstformen' },
  { v: 'Audubon plate', note: 'life-size, so the big birds are folded to fit the paper', q: 'Audubon Birds America' },
  { v: 'Doré engraving', note: 'a light source that is always theatrical and never justified', q: 'Gustave Dore engraving' },
  { v: 'chromolithograph trade card', note: 'commerce dressed up as a fairy tale', q: 'chromolithograph trade card' },
  { v: '19th-c. patent drawing', note: 'orthographic, numbered, section cuts hatched at 45°', q: 'patent drawing' },
  { v: 'Japonisme', note: 'Europe misunderstanding Japanese prints, productively', q: 'Japonisme' },
  { v: 'Morris pattern', note: 'a repeat you are not supposed to be able to find the edge of', q: 'William Morris wallpaper' },
  { v: 'Art Nouveau ironwork', note: 'the line is a plant carrying a structural load', q: 'Art Nouveau ironwork' },
  { v: 'Mucha lithograph', note: 'a woman, a halo, and a border of the same plant throughout', q: 'Mucha poster' },
  { v: 'Toulouse-Lautrec poster', note: 'flat spatter texture and a silhouette that carries the whole design', q: 'Toulouse-Lautrec poster' },
  { v: 'Currier & Ives', note: 'sentiment printed cheaply and coloured by hand in a line', q: 'Currier and Ives' },
  { v: 'mourning jewellery', note: 'a design woven from somebody\'s actual hair', q: 'mourning jewellery hair' },
  { v: 'phrenology diagram', note: 'confident labelled nonsense, beautifully drafted', q: 'phrenology head diagram' },
  { v: 'Ordnance Survey map', note: 'a hierarchy of line weights that encodes an entire landscape', q: 'Ordnance Survey map' },
  { v: 'celestial atlas plate', note: 'the constellation figure drawn over stars that ignore it', q: 'celestial atlas star chart' },
  { v: 'Pre-Raphaelite', note: 'everything in focus at once, which no eye has ever done', q: 'Pre-Raphaelite painting' },
  { v: 'Victorian cast-iron catalogue', note: 'ornament sold by the yard, drawn in strict elevation', q: 'cast iron catalogue ornament' },
  { v: 'Muybridge motion study', note: 'a movement broken into frames and laid out on a grid', q: 'Muybridge motion study' },

  // ---- The twentieth century
  { v: 'Sailor Jerry American traditional', note: 'black outline, five colours, engineered to still read in forty years', q: 'tattoo flash traditional' },
  { v: 'Bauhaus preliminary course', note: 'circle, square, triangle, three primaries, and nothing else at all', q: 'Bauhaus' },
  { v: 'Bauhaus weaving', note: 'a grid you cannot cheat, because the loom will not let you', q: 'Bauhaus textile weaving' },
  { v: 'constructivist poster', note: 'diagonal, red and black, type used as a structural member', q: 'constructivist poster' },
  { v: 'Suprematism', note: 'shapes floating on white with no ground and no scale', q: 'Malevich Suprematism' },
  { v: 'De Stijl', note: 'only horizontals, verticals, and the three primaries', q: 'De Stijl Mondrian' },
  { v: 'Futurist parole in libertà', note: 'typography arranged to be a noise rather than a sentence', q: 'Futurism Marinetti' },
  { v: 'Vorticism', note: 'the diagonal used as violence', q: 'Vorticism' },
  { v: 'Dada photomontage', note: 'scale mismatch as the entire technique', q: 'Dada photomontage' },
  { v: 'Surrealist automatism', note: 'draw first and find out what it was afterwards', q: 'Surrealism drawing' },
  { v: 'Art Deco', note: 'streamlining applied to things that do not move', q: 'Art Deco' },
  { v: 'Soviet space-programme graphic', note: 'optimism drawn entirely with a compass', q: 'Soviet space poster' },
  { v: 'WPA poster', note: 'three or four screens, flat, legible from a moving car', q: 'WPA poster' },
  { v: 'Swiss International Style', note: 'a grid, one sans face, and enormous restraint', q: 'Swiss typography poster' },
  { v: 'Ulm school', note: 'design treated as a branch of engineering, humourlessly', q: 'Ulm school design' },
  { v: 'Isotype pictogram', note: 'more of a thing is shown by more symbols, never a bigger one', q: 'Isotype Neurath' },
  { v: 'Polish poster school', note: 'a painter\'s hand doing a designer\'s job', q: 'Polish poster' },
  { v: 'op art', note: 'the eye does the work the ink didn\'t', q: 'op art' },
  { v: 'Ben-Day pop art', note: 'the printing artefact enlarged until it becomes the subject', q: 'Lichtenstein Ben-Day' },
  { v: 'psychedelic poster', note: 'lettering pushed to the exact edge of unreadable', q: 'psychedelic poster Fillmore' },
  { v: 'Memphis Group', note: 'laminate patterns and shapes that refuse to be tasteful', q: 'Memphis Group design' },
  { v: 'punk xerox collage', note: 'generation loss as a deliberate finish', q: 'punk fanzine' },
  { v: 'brutalist wayfinding', note: 'one weight, one grid, no ornament, no apology', q: 'brutalist architecture' },
  { v: 'Beck\'s diagram', note: 'geography sacrificed entirely to legibility', q: 'London Underground map' },
  { v: 'Shaker drawing', note: 'ornament treated as a moral failure', q: 'Shaker furniture' },
  { v: 'Bruno Munari\'s useless machines', note: 'engineering drawings for objects with no purpose', q: 'Bruno Munari' },
  { v: 'blueprint cyanotype', note: 'white line on blue, reversed out of the ground', q: 'cyanotype blueprint' },
  { v: 'Le Corbusier Modulor', note: 'proportion derived from a body and then imposed on everything', q: 'Modulor proportion' },

  // ---- Vernacular, technical and recent
  { v: 'sign painter\'s lettering', note: 'brush-made letterforms with a built-in speed', q: 'sign painting lettering' },
  { v: 'pinstriping', note: 'symmetrical freehand line laid down in one breath', q: 'pinstriping' },
  { v: 'graffiti wildstyle', note: 'letters interlocked until only the writers can read them', q: 'graffiti wildstyle' },
  { v: 'skate deck graphic', note: 'designed to be destroyed by use, and to look good doing it', q: 'skateboard deck graphic' },
  { v: 'hobo sign', note: 'a whole warning drawn in four chalk strokes on a gatepost', q: 'hobo sign' },
  { v: 'Pennsylvania Dutch hex sign', note: 'rotational symmetry deployed as protection', q: 'hex sign barn' },
  { v: 'Fraktur (Pennsylvania German)', note: 'a birth certificate as an excuse for a drawing', q: 'Fraktur Pennsylvania German' },
  { v: 'scherenschnitte', note: 'cut with scissors, so every line is a closed loop', q: 'scherenschnitte papercut' },
  { v: 'quilt block', note: 'a whole design built from one repeated right triangle', q: 'quilt block pattern' },
  { v: 'blackwork embroidery', note: 'counted thread; every stroke has to land on the weave', q: 'blackwork embroidery' },
  { v: 'papel picado', note: 'chiselled through forty sheets at once, so detail has a lower limit', q: 'papel picado' },
  { v: 'ex-voto retablo', note: 'the disaster on top, the thanks written underneath', q: 'ex voto retablo' },
  { v: 'exploded technical drawing', note: 'every part suspended along the axis it comes apart on', q: 'exploded view technical drawing' },
  { v: 'wiring diagram', note: 'topology only; physical position is a lie throughout', q: 'wiring diagram schematic' },
  { v: 'molecular structure diagram', note: 'bonds as sticks, and a convention for what points at you', q: 'molecular structure diagram' },
  { v: 'orthographic ship\'s lines plan', note: 'a hull described entirely by stacked contour curves', q: 'ship lines plan naval architecture' },
  { v: 'knitting chart', note: 'a picture that is also a set of instructions in a fixed order', q: 'knitting chart pattern' },
  { v: 'early sprite graphics', note: 'a recognisable creature inside 16 by 16 pixels and three colours', q: 'pixel art sprite' },
  { v: 'pen-plotter drawing', note: 'a machine holding one pen that cannot vary its pressure', q: 'plotter drawing' },
  { v: 'oscilloscope Lissajous trace', note: 'a curve produced by two frequencies arguing', q: 'Lissajous oscilloscope' },
  { v: 'matchbox label', note: 'a complete idea at 35 by 50 millimetres', q: 'matchbox label' },
  { v: 'fruit crate label', note: 'lurid colour applied to an entirely mundane product', q: 'fruit crate label' },
  { v: 'cigar band', note: 'gold embossing and heraldry wrapped around a cylinder', q: 'cigar band' },
  { v: 'circus poster', note: 'wood type at four sizes, all of them too large', q: 'circus poster' },
  { v: 'Voynich herbal', note: 'a plant that does not exist, drawn with total confidence', q: 'Voynich manuscript' },
  { v: 'seed catalogue plate', note: 'the vegetable rendered more beautiful than it will ever be', q: 'seed catalogue' },
  { v: 'field guide silhouette key', note: 'species distinguished only by outline, at a distance', q: 'bird silhouette identification' },
  { v: 'geological cross-section', note: 'time drawn as stacked hatching patterns', q: 'geological cross section' },
  { v: 'weather chart isobars', note: 'nested closed curves that describe an invisible surface', q: 'weather chart isobars' },
  { v: 'anatomical Chinese meridian chart', note: 'a body mapped with lines nobody can dissect', q: 'acupuncture meridian chart' },
];

// ------------------------------------------------------------------ technique
// How it is actually put into skin. Constrains the drawing before you draw.
export const TECHNIQUE = [
  { v: 'single needle, 0.18mm', note: 'hairline, and no forgiveness anywhere' },
  { v: 'bold-line blackwork, 9RL', note: 'one weight, no shading at all' },
  { v: 'three-needle liner, medium taper', note: 'a line with a little weight to it, and no delicacy' },
  { v: 'whip shading', note: 'grey that fades along the direction of the pull' },
  { v: 'pendulum shading', note: 'tone swung in arcs, so the gradient curves' },
  { v: 'dotwork stipple', note: 'tone made of dots you could in principle count' },
  { v: 'graduated stipple, four densities', note: 'value as a countable frequency, nothing in between' },
  { v: 'hand-poke', note: 'the irregularity of the line is the whole point' },
  { v: 'hand-poke, single dot per stroke', note: 'slow enough that you will change your mind halfway' },
  { v: 'white ink over solid black', note: 'the design is whatever wasn\'t blacked out' },
  { v: 'negative space only', note: 'you tattoo the ground; the figure is untouched skin' },
  { v: 'woodcut hatching', note: 'parallel lines that swell in the middle and taper at both ends' },
  { v: 'cross-hatch, two angles maximum', note: 'a third angle turns it to mud' },
  { v: 'contour hatching', note: 'the hatching follows the form, so it describes volume by itself' },
  { v: 'solid fill with a 1mm keyline gap', note: 'the gap is what makes it read' },
  { v: 'red and black only', note: 'no grey, no third colour, no negotiation' },
  { v: 'black and one dirty flesh tone', note: 'a palette that already looks thirty years old' },
  { v: 'ignorant style', note: 'deliberately clumsy line, done fast, meant it' },
  { v: 'burin engraving line', note: 'tapered at both ends, thickest where it turns' },
  { v: 'drypoint burr', note: 'a furred, soft-edged line that cannot be repeated' },
  { v: 'etched line, uniform width', note: 'acid does not care how hard you pressed' },
  { v: 'aquatint ground', note: 'a grain field instead of a gradient' },
  { v: 'mezzotint, worked from black to light', note: 'you remove darkness rather than add it' },
  { v: 'watercolour bleed, no outline', note: 'it will look bad in ten years — do it anyway' },
  { v: 'micro-realism inside 4cm', note: 'everything a photograph has, at the size of a stamp' },
  { v: 'ruler and compass only', note: 'no freehand curve is permitted' },
  { v: 'single-pass brush line', note: 'loaded once; where it runs dry, it runs dry' },
  { v: 'dry-brush drag', note: 'the broken edge of the stroke does the shading' },
  { v: 'heavy black with negative linework inside', note: 'the detail is cut out of the mass' },
  { v: 'satin-stitch embroidery look', note: 'ink pretending to be thread pretending to be ink' },
  { v: 'cross-stitch grid', note: 'every mark on a lattice, nothing between the cells' },
  { v: 'halftone dots at print scale', note: 'borrowed from a newspaper, at the wrong magnification' },
  { v: 'moiré from two overlaid screens', note: 'a pattern neither layer contains' },
  { v: 'raised keyline, scarification look', note: 'texture doing the job of contrast' },
  { v: 'blast-over existing work', note: 'it has to survive being drawn on top of something' },
  { v: 'lettering only, no image', note: 'the shape of the words has to carry the whole idea' },
  { v: 'one ink, three dilutions', note: 'value range is a budget, and it\'s small' },
  { v: 'rotary soft shading, no outline', note: 'edges defined only by where the tone stops' },
  { v: 'deliberate misregistration', note: 'the colour sits a millimetre off the line, on purpose' },
  { v: 'stencil-cut shapes, no linework', note: 'everything is an edge between two flats' },
  { v: 'linocut gouge marks left in', note: 'the tool\'s slips are part of the image' },
  { v: 'silhouette with one interior cut', note: 'a single window is all the detail you get' },
  { v: 'scratchboard, white line on black', note: 'you draw the light and the dark is a given' },
  { v: 'blind embossing, no ink', note: 'the image exists only as relief and shadow' },
  { v: 'chiaroscuro woodcut, three blocks', note: 'a key block and two flat tone blocks, nothing else' },
  { v: 'reduction print, one block', note: 'each colour destroys the possibility of the last' },
  { v: 'monotype, one impression only', note: 'a print that can never be pulled twice' },
  { v: 'sgraffito through a dark slip', note: 'scratch through the top layer to the colour beneath' },
  { v: 'champlevé cell and fill', note: 'every colour sits in its own walled compartment' },
  { v: 'cloisonné wire outline', note: 'the outline is a physical wall, so it can never be broken' },
  { v: 'niello inlay', note: 'black metal poured into an engraved groove and polished flush' },
  { v: 'repoussé from behind', note: 'the form is pushed out from the back and cleaned up from the front' },
  { v: 'chasing with a matting punch', note: 'texture applied one hammer blow at a time' },
  { v: 'stipple engraving, roulette', note: 'a wheel of teeth doing the work of a thousand dots' },
  { v: 'wood engraving on end grain', note: 'a line so fine the block outlives the press run' },
  { v: 'lino cut with a V-gouge only', note: 'every mark has the same wedge profile' },
  { v: 'pochoir, hand-cut stencils', note: 'flat gouache colour with a slight ridge at every edge' },
  { v: 'risograph two-colour overprint', note: 'a third colour that only exists where they overlap' },
  { v: 'photocopy generation loss', note: 'run it through five times and keep what survives' },
  { v: 'dot-matrix impact print', note: 'everything reduced to a coarse rectangular grid of pins' },
  { v: 'thermal receipt print', note: 'one colour, low contrast, guaranteed to fade' },
  { v: 'letterpress with visible bite', note: 'the impression is part of the image' },
  { v: 'rubber stamp, uneven inking', note: 'the same mark, never twice the same' },
  { v: 'potato-print repeat', note: 'a motif that degrades a little with each impression' },
  { v: 'resist and wash', note: 'you draw where the colour is forbidden to go' },
  { v: 'salt-and-ink bloom', note: 'the material decides the texture and you accept it' },
  { v: 'ink wash in five flat values', note: 'no gradients permitted, only steps' },
  { v: 'silverpoint', note: 'a line you cannot erase, that darkens for years afterwards' },
  { v: 'charcoal lifted with bread', note: 'the highlights are subtractions' },
  { v: 'conté on toned ground', note: 'the paper is the mid-tone; you add both ends' },
  { v: 'chalk on a wet ground', note: 'the mark spreads and you have to plan for it' },
  { v: 'ballpoint biro build-up', note: 'darkness only by accumulation, and it takes hours' },
  { v: 'fineliner, one nib, no lifting between marks', note: 'a drawing made of one enormous scribble' },
  { v: 'technical pen, three fixed widths', note: '0.1, 0.3, 0.7 and nothing else exists' },
  { v: 'brush pen, full pressure range', note: 'the width of the line is the emotional content' },
  { v: 'reed pen, cut blunt', note: 'the line splutters and you keep the splutter' },
  { v: 'quill sharpened halfway through', note: 'the first half and the second half do not match' },
  { v: 'airbrush with hard masks', note: 'soft gradients bounded by absolutely hard edges' },
  { v: 'spray through a torn stencil', note: 'a soft edge on one side and a hard one on the other' },
  { v: 'flat colour with a drop shadow offset 2mm', note: 'depth faked as cheaply as possible' },
  { v: 'engraved banknote guilloche', note: 'line spacing that shifts to describe a surface' },
  { v: 'contour map lines only', note: 'form described entirely by nested closed curves' },
  { v: 'isometric, no perspective', note: 'nothing gets smaller with distance, ever' },
  { v: 'orthographic, three views', note: 'plan, front and side, and you must infer the rest' },
  { v: 'exploded along one axis', note: 'the parts float apart in the order they assemble' },
  { v: 'cutaway with a torn edge', note: 'the interior revealed as though the skin were ripped' },
  { v: 'ghosted line for hidden parts', note: 'a dashed convention for what you cannot see' },
  { v: 'section hatched at 45°', note: 'the cut surface is a texture, everything else is line' },
  { v: 'wireframe with no hidden-line removal', note: 'you can see straight through the whole object' },
  { v: 'single-weight vector outline', note: 'no tapering anywhere, like a machine drew it' },
  { v: 'gradient mesh, no line at all', note: 'form entirely by colour transition' },
  { v: 'flat fills with 1-bit dithering', note: 'the only greys available are checkerboards' },
  { v: 'sprite at 16×16, three colours', note: 'the silhouette has to do everything' },
  { v: 'ASCII characters as tone', note: 'value chosen from a fixed alphabet of marks' },
  { v: 'chain-stitch on a hooped machine', note: 'a continuous line that cannot lift or cross itself easily' },
  { v: 'inlay with visible glue lines', note: 'the joins between materials are the drawing' },
  { v: 'burnt-in pyrography', note: 'darkness is a function of how long you held still' },
  { v: 'acid-etched into steel', note: 'the ground protects; the exposed metal is eaten away' },
  { v: 'sandblast through a mask', note: 'a frosted area with an absolutely crisp boundary' },
  { v: 'cut paper, no overlaps allowed', note: 'every shape must tile with its neighbours exactly' },
  { v: 'kirigami — cut and fold from one sheet', note: 'nothing is added and nothing is removed' },
  { v: 'tessellated fill, one tile', note: 'the entire interior is one shape repeating' },
];

// --------------------------------------------------------------------- format
// Where it lives on a body, which is a drawing problem before it is a taste one.
export const FORMAT = [
  { v: 'sternum, vertical, 22cm', note: 'symmetrical whether you like it or not' },
  { v: 'forearm wrap band', note: 'has to close cleanly at the seam and survive the twist' },
  { v: 'behind the ear, 3cm, no more', note: 'anything finer than 2mm will close up' },
  { v: 'spine column, one motif ×7, shrinking', note: 'the repeat is the composition' },
  { v: 'hand web and thumb crease', note: 'the worst-healing skin on the body' },
  { v: 'calf panel, read from behind, walking', note: 'nobody will ever see it standing still' },
  { v: 'ribs, following the curve of the 7th', note: 'the anatomy sets the baseline, not you' },
  { v: 'inner bicep, visible only when the arm lifts', note: 'a design with a condition attached' },
  { v: 'full back, 60% of it left empty', note: 'the emptiness is the expensive part' },
  { v: 'knuckle set, four characters', note: 'four chances, 14mm each' },
  { v: 'ankle cuff closing at the Achilles', note: 'the join lands where the skin moves most' },
  { v: 'shoulder cap under a t-shirt edge', note: 'the sleeve hem crops it; design for the crop' },
  { v: 'across the arm/rib seam, aligned standing', note: 'only correct in one posture' },
  { v: 'throat, horizontal, 5cm', note: 'no second attempt' },
  { v: 'two pieces on two people', note: 'neither one is finished alone' },
  { v: 'flash sheet, six designs, one line weight', note: 'they have to look like family' },
  { v: 'mirrored pair across the midline', note: 'the body isn\'t actually symmetrical — deal with it' },
  { v: 'a single 2cm mark and nothing else', note: 'all the meaning has to fit in one gesture' },
  { v: 'hip to knee, one composition', note: 'it crosses a joint that folds to 140°' },
  { v: 'inner forearm, oriented for the wearer', note: 'upside down to everyone else, and that\'s correct' },
  { v: 'wrapping a joint, full flexion', note: 'it has to still be the same shape when bent' },
  { v: 'under the collarbone, using it as a baseline', note: 'a bone as a typographic rule' },
  { v: 'nape, hidden under grown hair', note: 'it is shown by choice, never by default' },
  { v: 'foot arch — it will fade', note: 'accept the five-year lifespan up front' },
  { v: 'continuing onto the palm', note: 'the palm will reject most of it; plan which part' },
  { v: 'blackout band, subject in reserve', note: 'the band is the ink, the subject is skin' },
  { v: 'over an existing scar, using it', note: 'the scar is a given line in the drawing' },
  { v: '12cm square, framed like a print', note: 'a border on skin, which almost never works' },
  { v: 'outer upper arm, read across a room', note: 'designed for six metres, not for sixty centimetres' },
  { v: 'wrist, on the tendon side', note: 'moves constantly and heals badly' },
  { v: 'the whole of one finger, wrapped', note: 'a cylinder 15mm across with a joint in the middle' },
  { v: 'both shins, one design split', note: 'it only assembles when you stand with your feet together' },
  { v: 'armpit, into the hollow', note: 'a surface that is concave in two directions' },
  { v: 'the back of the knee', note: 'skin that folds completely shut several thousand times a day' },
  { v: 'elbow ditch to wrist, one sweep', note: 'a long thin field with a taper built into it' },
  { v: 'the crown of the head', note: 'it disappears entirely if the hair grows' },
  { v: 'a band that passes under the arm', note: 'half of it you will never see without a mirror' },
  { v: 'sacrum, horizontal', note: 'a wide short field over a bone that shows through' },
  { v: 'across both shoulder blades', note: 'the two halves move independently of each other' },
  { v: 'the side of the neck, vertical', note: 'it will be cropped by every collar you own' },
  { v: 'sternum to navel, narrow column', note: 'a 5cm-wide strip 40cm long' },
  { v: 'around the wrist as a bracelet', note: 'the seam must be invisible from every angle' },
  { v: 'inside the lower lip', note: 'it will be gone in three years and that is the point' },
  { v: 'behind the knee to the ankle', note: 'a field that is only flat when you are lying down' },
  { v: 'the outside of the little finger', note: 'about 8mm of usable width' },
  { v: 'a full sleeve with three unrelated subjects', note: 'the background has to reconcile them' },
  { v: 'chest panel that stops at the collar line', note: 'designed around a shirt you actually own' },
  { v: 'across the ribs on both sides, matching', note: 'two mirrored fields you cannot see at once' },
  { v: 'the top of the foot, over the tendons', note: 'the surface moves 10mm when you flex' },
  { v: 'a strip along the top of the shoulder', note: 'read from above, by other people' },
  { v: 'inner thigh, 20cm', note: 'the most private field on the body' },
  { v: 'from the wrist onto the back of the hand', note: 'it crosses the joint everyone looks at' },
  { v: 'three small pieces that only relate at a distance', note: 'a constellation rather than a picture' },
  { v: 'the outer edge of the forearm', note: 'a natural line the design must either follow or fight' },
  { v: 'one piece designed to be extended later', note: 'it must be finished and unfinished simultaneously' },
  { v: 'a border around an existing tattoo', note: 'you cannot change what is already there' },
  { v: 'filling the gap between two old pieces', note: 'the brief is entirely defined by what is around it' },
  { v: 'the hollow of the throat, 4cm', note: 'a hollow, so it distorts from every angle but one' },
  { v: 'the whole of the upper back, one line weight', note: 'a very large field with no tonal help' },
  { v: 'a horizontal band across the stomach', note: 'the field changes shape with every breath' },
  { v: 'the shoulder blade only, 15cm circle', note: 'a bone that slides under the skin as the arm moves' },
  { v: 'from behind the ear into the hairline', note: 'the boundary is hair, and hair moves' },
  { v: 'a piece that reads as a watch or a cuff', note: 'it has to look like an object, not a drawing' },
  { v: 'both forearms, forming one image when held together', note: 'correct in exactly one gesture' },
  { v: 'the fold of the elbow, 6cm', note: 'skin that creases in a fixed, predictable place' },
  { v: 'a vertical strip down the outside of the leg', note: '70cm long and 8cm wide' },
  { v: 'the heel', note: 'thick skin, poor healing, and constant abrasion' },
  { v: 'across the hips, following the iliac crest', note: 'a bone that gives you your baseline for free' },
  { v: 'a piece that finishes exactly at a tan line', note: 'the boundary is seasonal' },
  { v: 'one shoulder, designed to be seen in profile', note: 'the frontal view is not the view' },
  { v: 'a torso piece that avoids the midline entirely', note: 'symmetry is forbidden by the placement' },
  { v: 'the underside of the forearm, wrist to elbow', note: 'the softest and most legible skin available' },
  { v: 'a repeated motif down the outside of both arms', note: 'rhythm rather than image' },
  { v: 'a single line that crosses the whole body', note: 'it has to survive every joint it passes' },
  { v: 'the back of the upper arm', note: 'you will only ever see it in photographs' },
  { v: 'a small piece placed to be found, not displayed', note: 'somebody has to already know it is there' },
  { v: 'a piece read upside down by the wearer looking down', note: 'foreshortened from the only angle you get' },
  { v: 'shin, directly over the bone', note: 'almost no tissue between needle and bone' },
  { v: 'a panel that matches the shape of a pocket', note: 'an arbitrary frame you did not choose' },
  { v: 'a design that runs into an existing birthmark', note: 'the mark was there first and stays' },
  { v: 'temple, 3cm, in front of the hairline', note: 'permanently visible, permanently public' },
  { v: 'a piece split across two limbs by 20cm of skin', note: 'the gap is part of the composition' },
  { v: 'the whole hand, back and fingers', note: 'six planes, all moving relative to each other' },
  { v: 'a strip along the jawline', note: 'follows a bone that defines the face' },
  { v: 'across the top of the chest, collarbone to collarbone', note: 'wide, shallow, and bilaterally symmetrical' },
  { v: 'a small piece on the ball of the shoulder', note: 'a compound curve in every direction' },
  { v: 'the inside of the ankle', note: 'a bony prominence directly under thin skin' },
  { v: 'a design that reads as a scar rather than a tattoo', note: 'nobody should be sure it was chosen' },
  { v: 'a whole limb in one continuous field of black', note: 'the design is where the black is not' },
  { v: 'a piece meant to be photographed from directly above', note: 'the wearer\'s own view is the wrong one' },
  { v: 'ribs to hip, following the body\'s longest curve', note: 'the composition has to bend' },
  { v: 'a motif repeated at four different scales', note: 'placement determines which one you notice first' },
  { v: 'the outer thigh, seated view', note: 'design for the shape it makes when you sit down' },
  { v: 'a piece finished by a second artist later', note: 'you draw half and specify the rest' },
  { v: 'small enough to hide under a plaster', note: 'a size constraint from an entirely practical direction' },
  { v: 'across the throat and under the jaw', note: 'the least forgiving placement there is' },
  { v: 'a design that continues onto a fingernail', note: 'part of it grows out and has to be redrawn' },
  { v: 'inside the ear', note: 'a surface with no flat area at all' },
  { v: 'the whole forearm, but only in the negative', note: 'you blackout everything except the subject' },
];

// ----------------------------------------------------------------- constraint
// The hard rule. This is the axis that stops a brief being a mood board.
export const CONSTRAINT = [
  { v: 'It must still read at 2cm.' },
  { v: 'One continuous line. No lifts.' },
  { v: 'No closed shapes anywhere.' },
  { v: 'Straight lines only.' },
  { v: 'Exactly nine marks. Not ten.' },
  { v: 'Assume every line doubles in width over twenty years, and design for that.' },
  { v: 'Nothing may mirror anything else.' },
  { v: 'Two line weights maximum.' },
  { v: 'It must read the same upside down.' },
  { v: 'It must survive being reduced to a flat silhouette.' },
  { v: 'The subject may never be shown whole — only a part, at true size.' },
  { v: 'No faces.' },
  { v: 'The negative space must be a second, recognisable image.' },
  { v: 'Drawn from memory. No reference in front of you.' },
  { v: 'It must fit a circle and touch it at exactly three points.' },
  { v: 'No curve may exceed 90°.' },
  { v: 'Finished in one sitting, under two hours.' },
  { v: 'It has to look older than you are.' },
  { v: 'It must be legible through a shirt, as a shadow.' },
  { v: 'Nothing darker than 50% grey.' },
  { v: 'It must contain one genuine mistake, kept.' },
  { v: 'No element may appear twice.' },
  { v: 'Exactly one axis of symmetry, and it may not be vertical.' },
  { v: 'The wearer must be able to redraw it, badly, from memory.' },
  { v: 'It contains one number, and nothing else means anything.' },
  { v: 'It must work as a stamp, a stencil and a tattoo without changes.' },
  { v: 'The heaviest black sits at the edge, never at the centre.' },
  { v: 'No ornament. Every mark has to be structural.' },
  { v: 'A different artist must be able to finish it in ten years.' },
  { v: 'It must reward being close and still work at arm\'s length.' },
  { v: 'Whatever the obvious composition is, do the other one.' },
  { v: 'It may not touch the edge of its own bounding box.' },
  { v: 'One weight of line throughout, including the fill.' },
  { v: 'It must look unfinished on purpose, and be finished.' },
  { v: 'It has to survive being photocopied five times.' },
  { v: 'Every line must start and end at another line.' },
  { v: 'No line may cross another line.' },
  { v: 'Exactly three enclosed areas. No more, no fewer.' },
  { v: 'The composition must work rotated 90°, and mean something different.' },
  { v: 'No horizontal or vertical lines at all.' },
  { v: 'Only horizontals and verticals.' },
  { v: 'It must be drawable with a compass and a straight edge only.' },
  { v: 'The largest element may be no more than three times the smallest.' },
  { v: 'Half the marks must be shorter than 5mm.' },
  { v: 'It must have a clear top, and be wrong any other way up.' },
  { v: 'No detail smaller than 3mm survives; do not draw any.' },
  { v: 'It must occupy exactly half of its field. Measure it.' },
  { v: 'The outline alone must be enough. Add interior detail, then remove it.' },
  { v: 'Everything must touch at least one other thing.' },
  { v: 'Nothing may touch anything else.' },
  { v: 'It must be describable in one sentence over the phone.' },
  { v: 'It must be impossible to describe over the phone.' },
  { v: 'You may use only marks you can make in under one second.' },
  { v: 'Every curve must be an arc of the same circle.' },
  { v: 'The design must degrade gracefully — half of it, alone, still works.' },
  { v: 'It has to look right in a mirror, because that is where it will be seen.' },
  { v: 'No shape may be a shape you have drawn before.' },
  { v: 'The subject must be recognisable to someone who has never seen one.' },
  { v: 'It must not be recognisable to anyone but you.' },
  { v: 'Only one element may be curved. Everything else is straight.' },
  { v: 'It must read at speed, from a moving vehicle.' },
  { v: 'The eye must enter at one specific point. Design that entrance.' },
  { v: 'No gradient. Every transition is a hard edge.' },
  { v: 'It must be symmetrical in outline and asymmetrical inside.' },
  { v: 'The design must be older than any technique used to draw it.' },
  { v: 'It must survive being tattooed by someone having a bad day.' },
  { v: 'No more than 20% of the field may be inked.' },
  { v: 'At least 70% of the field must be solid black.' },
  { v: 'The composition must have no centre.' },
  { v: 'Everything must radiate from one point you never draw.' },
  { v: 'It must be finishable with the wrong hand.' },
  { v: 'Draw it once. Whatever happens is the design.' },
  { v: 'Draw it forty times and use the thirty-ninth.' },
  { v: 'It must contain something factually wrong, and be better for it.' },
  { v: 'Every proportion must come from measuring something real.' },
  { v: 'No proportion may be measured. Estimate everything.' },
  { v: 'It must work in one colour, and be ruined by two.' },
  { v: 'The heaviest element must be the least important one.' },
  { v: 'There must be exactly one place the eye can rest.' },
  { v: 'The design must imply something outside its own edges.' },
  { v: 'Nothing may extend beyond what is drawn. It is complete.' },
  { v: 'It must be readable by touch alone once healed.' },
  { v: 'The whole design must fit under a thumbnail. Then scale it up.' },
  { v: 'It has to hold together when squinted at from three metres.' },
  { v: 'Use no more than four distinct shapes, repeated.' },
  { v: 'Every element must be a different size. No two match.' },
  { v: 'Every element must be exactly the same size.' },
  { v: 'The design may contain no right angles.' },
  { v: 'Only right angles.' },
  { v: 'It must be possible to tile the design with itself.' },
  { v: 'No part may be drawn twice — if it repeats, it is one mark stretched.' },
  { v: 'It must survive the wearer gaining or losing fifteen kilos.' },
  { v: 'It must look better in ten years than it does healed.' },
  { v: 'It must be finished before you decide whether you like it.' },
  { v: 'Design the negative space first; the subject is whatever is left.' },
  { v: 'It must include one element borrowed from the wrong century.' },
  { v: 'The line weight must vary only where the form turns away.' },
  { v: 'It must be legible to a person who cannot see red.' },
  { v: 'It must not resemble anything currently on anyone\'s Instagram.' },
  { v: 'Nothing in it may be pointed.' },
  { v: 'Everything in it must be pointed.' },
  { v: 'The composition must lean. Nothing is level.' },
  { v: 'Absolute level and plumb throughout. Any drift is a failure.' },
  { v: 'One element must be twice as detailed as everything else combined.' },
  { v: 'Detail must be evenly distributed. No focal point at all.' },
  { v: 'It must be drawn at final size, never scaled.' },
  { v: 'It must be designed at ten times size and reduced.' },
  { v: 'It must work if the wearer never explains it.' },
  { v: 'It must be a question, not a statement.' },
  { v: 'It must be finished in the fewest marks you can manage, then one fewer.' },
  { v: 'Take the finished design and remove the best part.' },
  { v: 'The best part must be at the edge, half cropped.' },
  { v: 'It must be impossible to tell where you started.' },
  { v: 'It must be obvious where you started, and that must be the subject.' },
  { v: 'No two lines may be parallel.' },
  { v: 'All lines must be parallel or perpendicular to one axis.' },
  { v: 'It must survive being scaled to 40% without redrawing.' },
  { v: 'It must be drawn without ever lifting your eyes to look at it.' },
  { v: 'The design must contain its own frame, and break it once.' },
  { v: 'It must read differently to the wearer than to everyone else.' },
];

// ---------------------------------------------------------------------- twist
// The collision. Applied to the subject, after everything else is decided.
export const TWIST = [
  { v: 'crossed with a piece of obsolete hardware' },
  { v: 'as a diagram from a manual nobody kept' },
  { v: 'drawn by someone who was afraid of it' },
  { v: 'drawn by someone who owned one' },
  { v: 'seen from directly above' },
  { v: 'seen from underneath' },
  { v: 'the exact frame before impact' },
  { v: 'only the evidence, never the event' },
  { v: 'two of them, one of which is wrong' },
  { v: 'mid-moult, half out of the old one' },
  { v: 'rendered as a tool' },
  { v: 'rendered as a building' },
  { v: 'rendered as weather' },
  { v: 'wearing something' },
  { v: 'broken, and visibly repaired' },
  { v: 'as a constellation — only the joints marked' },
  { v: 'pressed flat, as if kept in a book' },
  { v: 'caught turning into something else' },
  { v: 'as a heraldic charge on a field' },
  { v: 'one part of it drawn in a completely different tradition' },
  { v: 'scaled wrong on purpose — a hand-sized thing at body scale' },
  { v: 'surrounded by an unreasonable amount of nothing' },
  { v: 'at night, but no shadows are drawn' },
  { v: 'only the parts that would be underwater' },
  { v: 'as it appears to whatever eats it' },
  { v: 'in a museum drawer, with a pin and a label' },
  { v: 'exactly as it is, with no interpretation whatsoever' },
  { v: 'from the reference photograph\'s worst angle' },
  { v: 'as a cover-up of something it used to be' },
  { v: 'held still for a very long exposure' },
  { v: 'as the negative of itself' },
  { v: 'partly obscured by the thing in front of it' },
  { v: 'at the scale a map would use' },
  { v: 'with its supporting structure showing' },
  { v: 'as a fossil of itself' },
  { v: 'as the tool that would be used to make it' },
  { v: 'in the moment it stops being useful' },
  { v: 'reassembled slightly wrong from memory' },
  { v: 'as a shadow only, with the object omitted' },
  { v: 'wet' },
  { v: 'frozen mid-collapse' },
  { v: 'as it looked before anyone had a word for it' },
  { v: 'drawn by someone who had it described to them once' },
  { v: 'with everything soft removed' },
  { v: 'with everything hard removed' },
  { v: 'shown only by what it displaces' },
  { v: 'as an instruction for how to make one' },
  { v: 'as the packaging it came in' },
  { v: 'with one component replaced by something from a different century' },
  { v: 'as a hole in the shape of itself' },
  { v: 'at the moment of maximum tension, not maximum motion' },
  { v: 'as it would be drawn on a warning sign' },
  { v: 'as a knot' },
  { v: 'unfolded flat, like a paper net' },
  { v: 'as a cross-section through its widest point' },
  { v: 'as a cross-section through the least interesting point' },
  { v: 'with the interior drawn and the exterior implied' },
  { v: 'growing out of something it has nothing to do with' },
  { v: 'as a container for something else' },
  { v: 'occupied by something living in it' },
  { v: 'as the trace it leaves behind when it moves' },
  { v: 'seen through something that distorts it' },
  { v: 'in the process of being taken apart by someone offscreen' },
  { v: 'as a specimen, badly mounted' },
  { v: 'as a specimen, mounted with obvious love' },
  { v: 'repeated until the repetition is the subject' },
  { v: 'exactly once, with no context at all' },
  { v: 'held' },
  { v: 'discarded' },
  { v: 'in the wrong environment entirely' },
  { v: 'made of the wrong material throughout' },
  { v: 'drawn as though it were dangerous, whether or not it is' },
  { v: 'drawn as though it were sacred, whether or not it is' },
  { v: 'reduced to the three marks that make it recognisable' },
  { v: 'with one of those three marks removed' },
  { v: 'in silhouette, but with one interior detail insisted upon' },
  { v: 'as the diagram a child would draw of it' },
  { v: 'as the diagram a patent lawyer would draw of it' },
  { v: 'at the exact moment it becomes symmetrical' },
  { v: 'from the angle it is never photographed from' },
  { v: 'wrapped in something' },
  { v: 'casting a shadow of a different object' },
  { v: 'with its own history drawn into its surface' },
  { v: 'brand new, which is the least interesting it will ever be' },
  { v: 'worn out past the point of function' },
  { v: 'as a pair, where the second is the first after time has passed' },
  { v: 'inside out' },
  { v: 'as though gravity came from the side' },
  { v: 'built out of many copies of a smaller version of itself' },
  { v: 'as one element of a set you never see the rest of' },
  { v: 'measured, with the measurements shown' },
  { v: 'drawn at the moment of its first use' },
  { v: 'drawn at the moment of its last' },
  { v: 'as a knot in the material it is made of' },
  { v: 'with its function inverted' },
  { v: 'as it would appear on an instrument reading' },
  { v: 'as it sounds' },
  { v: 'as a smell would be drawn, if you had to' },
  { v: 'as seen by something with no depth perception' },
  { v: 'with the important part deliberately cropped off' },
  { v: 'assembled from parts that do not belong to it' },
  { v: 'as the mould it would be cast in' },
  { v: 'balanced impossibly' },
  { v: 'exactly halfway through failing' },
  { v: 'as the reason for something else' },
  { v: 'as the result of something you never see' },
  { v: 'flattened by pressure from one direction' },
  { v: 'as a hinge' },
  { v: 'as though it were a letter in an alphabet' },
  { v: 'drawn as the map of somewhere' },
  { v: 'as it would look on the day it stops existing' },
  { v: 'with everything symmetrical made asymmetrical, and nothing else changed' },
  { v: 'drawn only where it touches something else' },
  { v: 'as the space around it, with the object left as skin' },
  { v: 'at the size it would be if it fit in a hand' },
  { v: 'with one small part rendered at ten times the detail of the rest' },
  { v: 'as a thing that is clearly about to move' },
  { v: 'as a thing that has never moved and never will' },
  { v: 'drawn by the light of the thing itself' },
];

// -------------------------------------------------------------------- objects
// The non-organism subjects. Used on roughly half of rolls, so the page isn't
// only ever a bestiary. Deliberately specific: a named thing beats a category,
// because "a bird" is a mood and "a nocturnal, the instrument" is a brief.
export const OBJECTS = [
  { v: 'a fluke anchor, stockless', q: 'anchor ship' },
  { v: 'a Geiger–Müller tube', q: 'scientific instrument tube' },
  { v: 'a Fresnel lens in section', q: 'lighthouse lens' },
  { v: 'an orrery gear train', q: 'orrery astronomical machine' },
  { v: 'the Antikythera fragment', q: 'ancient bronze mechanism' },
  { v: 'a whalebone corset stay', q: 'corset busk whalebone' },
  { v: 'a constrictor knot', q: 'knot rope' },
  { v: 'a rear derailleur at full travel', q: 'bicycle mechanism' },
  { v: 'a moth trap, lit', q: 'lantern trap' },
  { v: 'a plumb bob', q: 'plumb bob tool' },
  { v: 'a hurricane lamp', q: 'oil lamp glass' },
  { v: 'a Staunton knight', q: 'chess piece knight' },
  { v: 'a tuning fork', q: 'tuning fork' },
  { v: 'a bee smoker', q: 'beekeeping smoker' },
  { v: 'a hagstone', q: 'stone amulet pierced' },
  { v: 'a windmill\'s brake wheel', q: 'windmill mechanism wheel' },
  { v: 'an ammonite cut and polished', q: 'ammonite fossil' },
  { v: 'an eye splice in three-strand rope', q: 'rope splice' },
  { v: 'a diatom frustule', q: 'diatom microscope' },
  { v: 'a lock at the shear line', q: 'lock mechanism key' },
  { v: 'a corvid\'s cache, excavated', q: 'crow bird' },
  { v: 'the Pioneer plaque', q: 'Pioneer plaque' },
  { v: 'a Lichtenberg figure in oak', q: 'lightning tree' },
  { v: 'a mudlarked clay pipe', q: 'clay pipe fragment' },
  { v: 'a compass rose with one error in it', q: 'compass rose chart' },
  { v: 'a hand of cards, face down', q: 'playing cards' },
  { v: 'the arc of a signal flare', q: 'flare signal' },
  { v: 'a milk tooth', q: 'tooth' },
  { v: 'a bicycle chain in the S of its slack', q: 'chain' },
  { v: 'a hex bolt seen down its axis', q: 'bolt fastener' },
  { v: 'an oak gall, opened', q: 'oak gall' },
  { v: 'a wasp nest in cutaway', q: 'wasp nest paper' },
  { v: 'a beaver dam in section', q: 'beaver dam' },
  { v: 'a cuttlebone', q: 'cuttlefish bone' },
  { v: 'an obsidian core after flaking', q: 'obsidian blade knapped' },
  { v: 'a Dutch dijk cross-section', q: 'dike embankment section' },
  { v: 'an astrolabe\'s rete', q: 'astrolabe' },
  { v: 'a swift, which never lands', q: 'swift bird flight' },
  { v: 'a sourdough starter at peak', q: 'sourdough bread' },
  { v: 'the shipping forecast sea areas', q: 'nautical chart North Sea' },
  { v: 'a magnetotactic bacterium', q: 'bacteria micrograph' },
  { v: 'a caltrop', q: 'caltrop iron' },
  { v: 'a fish weir at low tide', q: 'fish trap weir' },
  { v: 'a printer\'s em quad', q: 'printing type metal' },
  { v: 'a swage block', q: 'blacksmith tool anvil' },
  { v: 'the inside of a barrel organ', q: 'barrel organ mechanism' },
  { v: 'a shepherd\'s tally in notches', q: 'tally stick' },
  { v: 'a heliograph mirror', q: 'heliograph signal mirror' },
  { v: 'a nocturnal, the instrument', q: 'nocturnal instrument navigation' },
  { v: 'a foundry pattern and its core box', q: 'foundry pattern casting' },
  { v: 'an escapement, stopped', q: 'clock escapement movement' },
  { v: 'a fogbow', q: 'fog bow' },
  { v: 'a Wardian case', q: 'terrarium glass case' },
  { v: 'a bone flute, five holes', q: 'bone flute prehistoric' },
  { v: 'a votive limb in tin', q: 'ex voto votive offering' },
  { v: 'a soil horizon profile', q: 'soil profile diagram' },
  { v: 'a sextant\'s index arm', q: 'sextant' },
  { v: 'a theodolite on its tripod', q: 'theodolite surveying' },
  { v: 'a pantograph', q: 'pantograph drawing instrument' },
  { v: 'a camera obscura', q: 'camera obscura' },
  { v: 'a zoetrope strip', q: 'zoetrope' },
  { v: 'a magic lantern slide', q: 'magic lantern slide' },
  { v: 'a stereoscope card', q: 'stereoscope card' },
  { v: 'a daguerreotype case, open', q: 'daguerreotype case' },
  { v: 'a Jacquard punch card', q: 'Jacquard loom card' },
  { v: 'a core memory plane', q: 'core memory computer' },
  { v: 'a vacuum tube, lit', q: 'vacuum tube valve' },
  { v: 'a slide rule at a setting', q: 'slide rule' },
  { v: 'an abacus mid-calculation', q: 'abacus' },
  { v: 'a quipu', q: 'quipu Inca' },
  { v: 'a Marconi spark-gap transmitter', q: 'spark gap transmitter' },
  { v: 'a crystal radio\'s cat\'s whisker', q: 'crystal radio' },
  { v: 'a telegraph key', q: 'telegraph key' },
  { v: 'a semaphore tower\'s arms', q: 'semaphore telegraph' },
  { v: 'a lighthouse\'s occulting mechanism', q: 'lighthouse mechanism' },
  { v: 'a bell and its clapper, silent', q: 'bell church' },
  { v: 'a carillon drum', q: 'carillon mechanism' },
  { v: 'a hurdy-gurdy wheel', q: 'hurdy gurdy' },
  { v: 'an organ pipe mouth', q: 'organ pipe' },
  { v: 'a reed in a harmonium', q: 'harmonium reed' },
  { v: 'a tuning peg and its wound string', q: 'violin tuning peg' },
  { v: 'a bow\'s frog', q: 'violin bow frog' },
  { v: 'a metronome, stopped off-beat', q: 'metronome' },
  { v: 'a music box comb', q: 'music box mechanism' },
  { v: 'a player-piano roll', q: 'player piano roll' },
  { v: 'a phonograph groove magnified', q: 'phonograph record groove' },
  { v: 'a wax cylinder', q: 'phonograph cylinder' },
  { v: 'a lathe\'s dead centre', q: 'lathe machine tool' },
  { v: 'a machinist\'s surface plate', q: 'machinist tools' },
  { v: 'a vernier caliper on a dimension', q: 'vernier caliper' },
  { v: 'a set of gauge blocks, wrung', q: 'gauge blocks metrology' },
  { v: 'a micrometer\'s thimble', q: 'micrometer' },
  { v: 'a try square against an edge', q: 'try square woodworking' },
  { v: 'a marking gauge\'s pin', q: 'marking gauge woodworking' },
  { v: 'a dovetail half-cut', q: 'dovetail joint' },
  { v: 'a mortise and its tenon, apart', q: 'mortise tenon joint' },
  { v: 'a scarf joint in a beam', q: 'scarf joint timber' },
  { v: 'a cruck frame', q: 'cruck frame timber building' },
  { v: 'a keystone at the moment of centring', q: 'arch keystone' },
  { v: 'a flying buttress in isolation', q: 'flying buttress' },
  { v: 'a corbelled vault', q: 'corbel vault' },
  { v: 'a drystone wall\'s through-stone', q: 'drystone wall' },
  { v: 'a hedge laid and pleached', q: 'hedge laying' },
  { v: 'a coppiced stool', q: 'coppice woodland' },
  { v: 'a pollarded willow', q: 'pollard willow' },
  { v: 'a grafted union in bark', q: 'graft tree' },
  { v: 'a seed drill\'s coulter', q: 'seed drill agriculture' },
  { v: 'a scythe\'s snath and its two nibs', q: 'scythe' },
  { v: 'a threshing flail', q: 'flail threshing' },
  { v: 'a quern stone\'s dressing', q: 'quern stone' },
  { v: 'a beehive\'s brood frame', q: 'beehive frame' },
  { v: 'a dovecote\'s nesting boxes', q: 'dovecote' },
  { v: 'an eel trap', q: 'eel trap' },
  { v: 'a lobster creel', q: 'lobster pot creel' },
  { v: 'a net-mending needle', q: 'net needle fishing' },
  { v: 'a harpoon with a toggling head', q: 'harpoon toggle' },
  { v: 'a kayak frame without its skin', q: 'kayak frame Inuit' },
  { v: 'a coracle', q: 'coracle boat' },
  { v: 'a clinker hull\'s overlap', q: 'clinker boat building' },
  { v: 'a ship\'s knee, grown to shape', q: 'ship knee timber' },
  { v: 'a capstan and its bars', q: 'capstan ship' },
  { v: 'a deadeye and its lanyard', q: 'deadeye rigging' },
  { v: 'a Turk\'s head knot', q: 'Turks head knot' },
  { v: 'a monkey\'s fist', q: 'monkey fist knot' },
  { v: 'a sailmaker\'s palm', q: 'sailmaker palm' },
  { v: 'a signal flag hoist', q: 'signal flags maritime' },
  { v: 'a lead line with its markings', q: 'sounding lead line' },
  { v: 'a traverse board', q: 'traverse board navigation' },
  { v: 'a chip log and its reel', q: 'chip log navigation' },
  { v: 'a binnacle and its correcting spheres', q: 'binnacle compass' },
  { v: 'an anemometer\'s cups', q: 'anemometer' },
  { v: 'a Stevenson screen', q: 'Stevenson screen weather' },
  { v: 'a barograph\'s week of trace', q: 'barograph' },
  { v: 'a seismograph drum', q: 'seismograph' },
  { v: 'a sundial\'s gnomon at the wrong latitude', q: 'sundial gnomon' },
  { v: 'a water clock\'s float', q: 'water clock clepsydra' },
  { v: 'an hourglass with the sand stopped', q: 'hourglass' },
  { v: 'a candle clock', q: 'candle clock' },
  { v: 'a marine chronometer in gimbals', q: 'marine chronometer' },
  { v: 'a tide-predicting machine', q: 'tide predicting machine' },
  { v: 'a planimeter tracing an area', q: 'planimeter' },
  { v: 'a Curta calculator', q: 'mechanical calculator' },
  { v: 'a nomogram', q: 'nomogram chart' },
  { v: 'a Smith chart', q: 'Smith chart' },
  { v: 'a Voronoi cell boundary', q: 'Voronoi diagram' },
  { v: 'a soap film on a wire frame', q: 'soap film minimal surface' },
  { v: 'a Chladni figure', q: 'Chladni figure' },
  { v: 'a Newton\'s rings interference pattern', q: 'Newton rings interference' },
  { v: 'a cloud chamber track', q: 'cloud chamber particle' },
  { v: 'a Foucault pendulum\'s sand', q: 'Foucault pendulum' },
  { v: 'a Wimshurst machine', q: 'Wimshurst machine' },
  { v: 'a Van de Graaff belt', q: 'Van de Graaff generator' },
  { v: 'a Tesla coil\'s toroid', q: 'Tesla coil' },
  { v: 'a Crookes tube', q: 'Crookes tube' },
  { v: 'a spectroscope\'s prism train', q: 'spectroscope prism' },
  { v: 'an emission spectrum as a barcode', q: 'emission spectrum lines' },
  { v: 'a phase-contrast microscope\'s condenser', q: 'microscope condenser' },
  { v: 'a herbarium sheet with its label', q: 'herbarium sheet' },
  { v: 'an entomologist\'s setting board', q: 'insect setting board' },
  { v: 'a study skin with its tag', q: 'bird study skin museum' },
  { v: 'a plaster death mask', q: 'death mask' },
  { v: 'a trepanned skull, healed', q: 'trepanation skull' },
  { v: 'an anatomical Venus', q: 'anatomical Venus wax' },
  { v: 'a Wunderkammer nautilus cup', q: 'nautilus cup' },
  { v: 'a memento mori ring', q: 'memento mori ring' },
  { v: 'a reliquary\'s window', q: 'reliquary' },
  { v: 'a pilgrim badge, cast in lead', q: 'pilgrim badge' },
  { v: 'a votive anatomical ex-voto in silver', q: 'ex voto silver' },
  { v: 'a rosary\'s decade', q: 'rosary beads' },
  { v: 'a prayer wheel\'s scroll', q: 'prayer wheel Tibetan' },
  { v: 'a bell-beaker\'s comb impression', q: 'beaker pottery prehistoric' },
  { v: 'a Roman fibula\'s spring', q: 'fibula brooch Roman' },
  { v: 'a torc\'s terminals', q: 'torc gold Celtic' },
  { v: 'a hoard, laid out on a table', q: 'hoard treasure archaeology' },
  { v: 'a bog body\'s plaited belt', q: 'bog body' },
  { v: 'a Sutton Hoo shoulder clasp', q: 'Sutton Hoo' },
  { v: 'a chess piece carved from walrus ivory', q: 'Lewis chessmen' },
  { v: 'a tally of a debt, split', q: 'tally stick exchequer' },
  { v: 'a wax seal, broken', q: 'wax seal matrix' },
  { v: 'a signet ring\'s intaglio', q: 'signet ring intaglio' },
  { v: 'a printing forme, locked up', q: 'printing forme chase' },
  { v: 'a compositor\'s stick', q: 'composing stick type' },
  { v: 'a type punch and its matrix', q: 'type punch matrix' },
  { v: 'a woodblock, inked but unprinted', q: 'woodblock printing block' },
  { v: 'a lithographic stone', q: 'lithographic stone' },
  { v: 'a bookbinder\'s sewing frame', q: 'bookbinding sewing frame' },
  { v: 'a marbled endpaper', q: 'marbled endpaper' },
  { v: 'a watermark seen against the light', q: 'watermark paper' },
  { v: 'a palimpsest under raking light', q: 'palimpsest manuscript' },
  { v: 'a scribe\'s pricking and ruling', q: 'manuscript ruling pricking' },
  { v: 'a girdle book', q: 'girdle book' },
  { v: 'a chained library\'s chain', q: 'chained library' },
  { v: 'an orrery\'s missing planet', q: 'orrery planetarium' },
  { v: 'a camera lucida', q: 'camera lucida' },
  { v: 'a claude glass', q: 'Claude glass' },
  { v: 'a perspective machine', q: 'perspective machine drawing' },
  { v: 'a lay figure, jointed', q: 'artist lay figure mannequin' },
  { v: 'a colour wheel with one segment wrong', q: 'colour wheel' },
  { v: 'a Munsell colour tree', q: 'Munsell colour system' },
  { v: 'a pigment grinding muller', q: 'pigment muller grinding' },
  { v: 'a gilder\'s cushion and knife', q: 'gilding tools gold leaf' },
  { v: 'a mordant-bitten plate', q: 'etching plate' },
  { v: 'a burnisher and a scraper', q: 'burnisher scraper engraving' },
  { v: 'a glassblower\'s pontil mark', q: 'pontil mark glass' },
  { v: 'a kiln\'s pyrometric cone, slumped', q: 'pyrometric cone kiln' },
  { v: 'a potter\'s rib', q: 'potter rib tool' },
  { v: 'a saggar', q: 'saggar kiln pottery' },
  { v: 'a crucible and its tongs', q: 'crucible tongs' },
  { v: 'a bloomery\'s slag', q: 'bloomery iron slag' },
  { v: 'a pattern-welded blade\'s figure', q: 'pattern welded blade' },
  { v: 'a file\'s cut, magnified', q: 'file tool metalwork' },
  { v: 'a tap and die', q: 'tap and die thread' },
  { v: 'a left-hand thread', q: 'screw thread' },
  { v: 'a Geneva drive', q: 'Geneva drive mechanism' },
  { v: 'a cam and its follower', q: 'cam follower mechanism' },
  { v: 'a differential gear', q: 'differential gear' },
  { v: 'an epicyclic gear train', q: 'epicyclic gear' },
  { v: 'a worm and wheel', q: 'worm gear' },
  { v: 'a ratchet and pawl', q: 'ratchet pawl mechanism' },
  { v: 'a Belleville washer stack', q: 'spring washer' },
  { v: 'a leaf spring, unloaded', q: 'leaf spring' },
  { v: 'a shock cord\'s core', q: 'bungee cord' },
  { v: 'a carabiner\'s gate', q: 'carabiner climbing' },
  { v: 'a Prusik hitch under load', q: 'Prusik knot climbing' },
  { v: 'a piton in a crack', q: 'piton climbing' },
  { v: 'an ice axe\'s adze', q: 'ice axe' },
  { v: 'a crampon\'s front points', q: 'crampon' },
  { v: 'a snowshoe\'s webbing', q: 'snowshoe' },
  { v: 'a sled\'s lashed joint', q: 'dog sled Inuit' },
  { v: 'a wind-scoured sastruga', q: 'sastruga snow' },
  { v: 'a cairn built by someone else', q: 'cairn stone' },
  { v: 'a trig point', q: 'trig point triangulation pillar' },
  { v: 'a boundary stone with two parishes on it', q: 'boundary stone' },
  { v: 'a milestone worn illegible', q: 'milestone' },
  { v: 'a benchmark cut into a wall', q: 'benchmark survey mark' },
  { v: 'a flood marker\'s highest line', q: 'flood marker high water' },
  { v: 'a lock gate\'s mitre', q: 'canal lock gate' },
  { v: 'a sluice and its rack', q: 'sluice gate' },
  { v: 'an Archimedes screw', q: 'Archimedes screw' },
  { v: 'a noria\'s pots', q: 'noria water wheel' },
  { v: 'a qanat shaft seen from above', q: 'qanat' },
  { v: 'a stepwell\'s inverted stair', q: 'stepwell India' },
  { v: 'an aqueduct\'s inspection cover', q: 'aqueduct' },
  { v: 'a Roman hypocaust\'s pillars', q: 'hypocaust' },
  { v: 'an icehouse in section', q: 'icehouse' },
  { v: 'a dovetailed granary on staddle stones', q: 'staddle stone granary' },
  { v: 'a lightning conductor\'s earth', q: 'lightning rod' },
  { v: 'a weathervane\'s cardinals', q: 'weathervane' },
  { v: 'a church clock with one hand', q: 'church clock single hand' },
  { v: 'a tide mill\'s pond', q: 'tide mill' },
  { v: 'a mill\'s tentering gear', q: 'windmill mechanism' },
  { v: 'a horse gin', q: 'horse gin mine' },
  { v: 'a Davy lamp\'s gauze', q: 'Davy lamp' },
  { v: 'a canary\'s cage with a resuscitator', q: 'mine canary cage' },
  { v: 'a pit prop under load', q: 'mine timber prop' },
  { v: 'a spoil heap\'s angle of repose', q: 'spoil heap mine' },
  { v: 'a core sample in its tray', q: 'drill core sample' },
  { v: 'a fault drawn in a section', q: 'geological fault diagram' },
  { v: 'a glacial erratic', q: 'glacial erratic' },
  { v: 'a dendritic drainage pattern', q: 'drainage pattern river' },
  { v: 'an oxbow, cut off', q: 'oxbow lake' },
  { v: 'a salt pan\'s polygons', q: 'salt pan polygons' },
  { v: 'a murmuration\'s density front', q: 'starling murmuration' },
  { v: 'a beach\'s cusp spacing', q: 'beach cusps' },
  { v: 'a wave train refracting round a headland', q: 'wave refraction coast' },
  { v: 'a Bénard convection cell', q: 'convection cells' },
  { v: 'a von Kármán vortex street', q: 'Karman vortex street' },
  { v: 'a shock diamond in an exhaust', q: 'shock diamond exhaust' },
  { v: 'a Schlieren image of a candle', q: 'Schlieren photography' },
  { v: 'a frost flower on glass', q: 'frost flower window' },
  { v: 'a snowflake under a lens', q: 'snowflake microscope' },
  { v: 'a hailstone in section', q: 'hailstone' },
  { v: 'a halo with its sun dogs', q: 'sun dog halo' },
  { v: 'a green flash', q: 'green flash sunset' },
  { v: 'a noctilucent cloud', q: 'noctilucent cloud' },
  { v: 'an aurora\'s curtain fold', q: 'aurora' },
  { v: 'a meteorite\'s Widmanstätten pattern', q: 'Widmanstatten pattern meteorite' },
  { v: 'a tektite', q: 'tektite' },
  { v: 'an impact crater\'s central peak', q: 'impact crater' },
  { v: 'a lunar libration cycle', q: 'moon phases' },
  { v: 'an analemma', q: 'analemma' },
  { v: 'a transit of Venus, timed', q: 'transit of Venus' },
  { v: 'an eclipse\'s shadow bands', q: 'solar eclipse' },
  { v: 'a radio telescope\'s feed horn', q: 'radio telescope' },
  { v: 'a Golden Record\'s cover diagram', q: 'Voyager Golden Record' },
  { v: 'a reentry capsule\'s ablated shield', q: 'reentry capsule heat shield' },
  { v: 'a parachute\'s reefing line', q: 'parachute' },
  { v: 'a windsock in a crosswind', q: 'windsock' },
  { v: 'a glider\'s tow release', q: 'glider aircraft' },
  { v: 'a propeller\'s twist along its span', q: 'propeller blade' },
  { v: 'a wing rib without its skin', q: 'aircraft wing rib' },
  { v: 'a control-line stunt handle', q: 'control line model aircraft' },
  { v: 'a kite\'s bridle', q: 'kite bridle' },
  { v: 'a boomerang\'s aerofoil section', q: 'boomerang' },
  { v: 'an atlatl and its dart', q: 'atlatl spear thrower' },
  { v: 'a bow\'s tiller, drawn', q: 'longbow archery' },
  { v: 'a fletching jig', q: 'arrow fletching' },
  { v: 'a crossbow\'s nut', q: 'crossbow mechanism' },
  { v: 'a trebuchet\'s counterweight', q: 'trebuchet' },
  { v: 'a portcullis half-raised', q: 'portcullis' },
  { v: 'a murder hole seen from below', q: 'castle machicolation' },
  { v: 'a star fort\'s bastion angles', q: 'star fort bastion' },
  { v: 'a chevaux de frise', q: 'chevaux de frise' },
  { v: 'a mantrap, sprung', q: 'mantrap iron' },
  { v: 'a fyke net\'s throat', q: 'fyke net' },
  { v: 'a decoy pipe on a duck pond', q: 'duck decoy pond' },
  { v: 'a falconer\'s hood', q: 'falconry hood' },
  { v: 'a jess and its swivel', q: 'falconry jess' },
  { v: 'a pigeon\'s message capsule', q: 'carrier pigeon message' },
  { v: 'a bee\'s waggle, plotted', q: 'bee waggle dance' },
  { v: 'an ant lion\'s pit', q: 'antlion pit' },
  { v: 'a caddisfly case built from gold', q: 'caddisfly case' },
  { v: 'a bowerbird\'s arrangement', q: 'bowerbird bower' },
  { v: 'a weaver\'s knot in a nest', q: 'weaver bird nest' },
  { v: 'a termite mound\'s ventilation section', q: 'termite mound' },
  { v: 'a spider\'s stabilimentum', q: 'spider web stabilimentum' },
  { v: 'a slime mould solving a maze', q: 'slime mould' },
  { v: 'a mycelial mat at the edge of a log', q: 'mycelium fungus' },
  { v: 'a lichen\'s growth ring', q: 'lichen rock' },
  { v: 'a tree\'s compression wood', q: 'tree rings cross section' },
  { v: 'a burl cut open', q: 'wood burl' },
  { v: 'a nurse log', q: 'nurse log forest' },
  { v: 'a witch\'s broom in a conifer', q: 'witches broom tree' },
  { v: 'a gall wasp\'s chamber', q: 'gall wasp' },
  { v: 'a leaf skeletonised to its veins', q: 'leaf skeleton veins' },
  { v: 'a seed\'s samara wing', q: 'samara seed' },
  { v: 'a pine cone opening as it dries', q: 'pine cone' },
  { v: 'a fern\'s unrolling crozier', q: 'fern fiddlehead' },
  { v: 'a phyllotactic spiral, counted', q: 'phyllotaxis spiral' },
  { v: 'a pollen grain\'s sculpturing', q: 'pollen grain microscope' },
  { v: 'a radiolarian test', q: 'radiolaria' },
  { v: 'a foraminiferan\'s chambers', q: 'foraminifera' },
  { v: 'a coccolithophore\'s plates', q: 'coccolithophore' },
  { v: 'a sea urchin\'s Aristotle\'s lantern', q: 'sea urchin Aristotle lantern' },
  { v: 'a barnacle\'s cirri, feeding', q: 'barnacle' },
  { v: 'an otolith\'s growth rings', q: 'otolith fish' },
  { v: 'a shark\'s dermal denticle', q: 'dermal denticle shark skin' },
  { v: 'a feather\'s barbule hooks', q: 'feather barbule microscope' },
  { v: 'a beak adapted past usefulness', q: 'bird beak skull' },
  { v: 'an egg tooth', q: 'egg tooth hatching' },
  { v: 'a bone\'s trabecular structure', q: 'trabecular bone' },
  { v: 'a suture line in a skull', q: 'skull suture' },
  { v: 'an antler\'s pedicle after casting', q: 'antler shed' },
  { v: 'a hoof in section', q: 'horse hoof anatomy' },
  { v: 'a baleen plate\'s fringe', q: 'baleen whale' },
  { v: 'a vestigial pelvis in a whale', q: 'whale skeleton' },
  { v: 'a coprolite', q: 'coprolite fossil' },
  { v: 'a trace fossil of a burrow', q: 'trace fossil burrow' },
  { v: 'a trilobite\'s schizochroal eye', q: 'trilobite eye' },
  { v: 'an amber inclusion', q: 'amber inclusion insect' },
  { v: 'a stromatolite in section', q: 'stromatolite' },
  { v: 'a banded iron formation', q: 'banded iron formation' },
];

// The kingdoms the taxonomic walk starts from, and how often. Weighted away
// from a pure Animalia bias so fungi, plants and protists get a real turn.
export const ROOTS = [
  { id: 1, name: 'Animalia', w: 0.52 },
  { id: 47126, name: 'Plantae', w: 0.17 },
  { id: 47170, name: 'Fungi', w: 0.17 },
  { id: 47686, name: 'Protozoa', w: 0.07 },
  { id: 48222, name: 'Chromista', w: 0.07 },
];

export const DECKS = { lineage: LINEAGE, technique: TECHNIQUE, format: FORMAT, constraint: CONSTRAINT, twist: TWIST, object: OBJECTS };
